# YAML file that provides parameters for tube_world simulation
tube_radius: 0.0762
robot_radius: 0.095
tube1_location: [0.5, 0.5]
tube2_location: [-0.5, -0.5]
tube3_location: [1.0, 1.0]
tube4_location: [-1.0, -1.0]
tube5_location: [-0.75, 0.75]
tube6_location: [0.75, -0.75]

sens_covMat: [0.1, 0.0, 0.0, 0.1]
tube_var: 0.001
max_range: 1.0
twist_noise: 0.0
slip_min: 0.1
slip_max: 0.5